queue:
  name: AzureHostedAgents
  timeoutInMinutes: 600

steps:
- task: AzurePowerShell@2
  inputs:
    azureConnectionType: 'ConnectedServiceNameARM'
    azureSubscription: '$(AzureConnectionName)'
    ScriptPath: 'Build.ps1'
    ScriptArguments: '-Location "$(Location)" -PackerFile "$(PackerFile)" -ClientId "$(ClientId)" -ClientSecret "$(ClientSecret)" -TenantId "$(TenantId)" -SubscriptionId "$(SubscriptionId)" -ObjectId "$(ObjectId)" -ManagedImageResourceGroupName "$(ManagedImageResourceGroupName)" -ManagedImageName "$(ManagedImageName)"'
    azurePowerShellVersion: 'LatestVersion'